# litellm_config.yaml
model_list:
  - model_name: Qwen3-4B-Thinking
    litellm_params:
      model: openai/qwen3-4b-thinking-2507
      api_base: http://127.0.0.1:8080/  
      api_key: fudgeoff              

  #Reflection
  - model_name: gpt-5
    litellm_params:
      model: openai/gpt-5

